### ISSUE TITLE
how to execute in bash of cmder

### ISSUE THREAD

**Issue by wushuzh** [zmwangx/chocolatey-googler#1]
When I installed googler successfully, I cannot run it in bash mode of cmder.

  The startup cmd is `cmd /c "%ConEmuDir%\..\git-for-windows\bin\bash --login -i"`

While everything works fine with cmd mode. 

  The startup cmd is `cmd /k "%ConEmuDir%\..\init.bat"`

If there is anything I should config for bash to be able to use googler.py there ?

```
λ which googler.py
/c/ProgramData/chocolatey/lib/googler/tools/googler/googler.py

λ googler.py hello world
/usr/bin/env: ‘python3’: No such file or directory
```

**Comment by zmwangx** [comment]
I'm primarily a macOS user and only use Windows sparingly, so I don't presume to know much about Windows, but I don't think Git for Windows (where your bash comes from) bundles Python 3. Any reason you can't use googler in cmd or PowerShell?

There's also [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) which is a full Linux experience on top of Windows 10, although that falls outside the scope of the Chocolatey package.

**Comment by zmwangx** [comment]
Closing due to lack of response.

**Comment by wushuzh** [comment]
I dont think I am using any bundled python. In fact, I installed python3 using chocolatey.

Maybe python3 can only be launched by **python** instead of _**python3**_ in my system as below. 

My guess is that the Shebang of googler.py is `#!/usr/bin/env python3`, maybe there is another way of saying the samething but still understandable in bash mode.

Here is my trying in bash mode of cmder (cmder installed by chocolatey as well)

```
λ python3
bash: python3: command not found

λ which python
/c/Python37/python

λ python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

λ which googler.py
/c/ProgramData/chocolatey/lib/googler/tools/googler/googler.py

λ googler.py hello world
/usr/bin/env: ‘python3’: No such file or directory
```

**Comment by wushuzh** [comment]
Sorry, I did not response since I was on trip last few days. In case you still have some suggestion on this issue, please kindly share with me :)

**Comment by zmwangx** [comment]
`python3` is the standard executable name on Unix-like systems, in accordance with [PEP 394](https://www.python.org/dev/peps/pep-0394/). The shebang is just part of the script (verbatim) and isn't meant to be special in the case of the Chocolatey package; instead it relies on `PATHEXT` to be executable (see https://docs.python.org/3/using/windows.html). It just so happens that git bash is MinGW and sees the shebang as special. (That you need to type `googler.py` instead of just `googler` to get to this "sort of works" situation is further proof that it's not intended to work at all.)

Does it work if you change the shebang to `#!/usr/bin/env python` in `/c/ProgramData/chocolatey/lib/googler/tools/googler/googler.py`? It will require manually editing the script every time you upgrade, which apparently isn't ideal, but I'm afraid I don't want to change package `googler.py` since it will make [VERIFICATION.txt](https://github.com/zmwangx/chocolatey-googler/blob/master/legal/VERIFICATION.txt) that much more complicated.

Alternatively, maybe you can create a `python3` symlink for `/c/Python37/python` and put it on your `PATH`. (I can elaborate if you don't know how to do it.)

Still, I recommend **using Chocolatey-installed googler in its supported environment, i.e., cmd or PowerShell.** To **properly install googler in a MinGW environment**, you probably want to follow this instead: https://github.com/jarun/googler#downloading-a-single-file.

**Comment by wushuzh** [comment]
Thanks for your answer.

I changed shebang as your suggested as `#!/usr/bin/env python`. The tests are done in Powershell/CMD/git-bash. There is no `python3: No such file or directory`. msg any more. 

But I got a 'No results' output when I execute ` googler.py -p myproxy hello world`. I also tried the same cmd without proxy option since my powershell/cmd/bash already has proxy setup and I can successfully do `curl google.com`. But I guess the proxy is another topic I should study.

I previously thought youtube-dl is a python project and I want to see how it handle this python interpreter issue. But it tured out it's been converted as a exe file. 

I just saw one issue [(python3) Use shims instead of PrependPath. Provide python3-shim.](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1128) I did not fully understand all the discussions yet. Anyway, I am not sure after 7 month, python2 retirement may help this issue better :)

**Comment by zmwangx** [comment]
> No results

That's https://github.com/jarun/googler/issues/286. The 3.9 update has been submitted to Chocolatey, but their review process is always slow. Again, I recommend https://github.com/jarun/googler#downloading-a-single-file as the proper channel for installation within MinGW.

> ytdl

They bundle a Python interpreter with their exe. That's too much of an overkill for googler, which is (expressly designed as) a single script.

> python2 EOL

No, it won't help in the foreseeable future. As I said, the `python3` command is a long established convention formalized in PEP 394. Very few distros decided to repurpose the `python` command when they migrated out of Python 2, so the `#!/usr/bin/env python3` shebang isn't going anywhere.

**Comment by zmwangx** [comment]
(Sorry, I had a wrong issue link on my clipboard. The link has been corrected.)
