### ISSUE TITLE
Github actions don't work

### ISSUE THREAD

**Issue by Gesparo** [zmwangx/chocolatey-googler#3]
Hello @zmwangx.

Your action "**Check and update to latest release**" doesn't work because of this problem "_This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days._". Can you check and rerun it?

**Comment by zmwangx** [comment]
Thanks for letting me know! I fixed the action and 4.3.2 has been submitted: https://community.chocolatey.org/packages/googler/4.3.2

**Comment by Gesparo** [comment]
Thank you for your quick response and fix). And, please update the dependency of Python to 3.6.0 in the .nuspec file
`
<dependencies>
      <dependency id="python" version="3.6.0" />
    </dependencies>
`
because of [documentation](https://github.com/jarun/googler#dependencies). I have checked googler 4.3.2 on python 3.6.8 and it works well.

**Comment by zmwangx** [comment]
We bump the required Python version in README when an old Python release goes EOL to signal that we may break compatibility and won't shoulder the support burden any more, but AFAIK we never introduced any new feature from py36 (because py35 or even py34 was pleasant enough to work with already). Also the version in nuspec is just the absolute minimum version, so since 4.3.2 has passed review already I'll just leave it. I'll bump the Python version for future releases.
